version: '3'
services:
  mongo:
    image: mongo:4.2.2
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./docker/mongo/data:/daba/db